
import { motion } from "framer-motion";
import { useState } from "react";
import hairreductionImg from "../Dermatology_img/hair-reduction.png"
import { ChevronRight } from "lucide-react";
import DermatologyHero from "../DermatoloyHero";
import DermatologyNav from "../DermatologyNav";
import DermatologyFooter from "../DermatologyFooter";

const TattoRemovel = () => {
  const infections = [
    { title: "Athlete's Foot", content: "Athlete's Foot (Tinea Pedis) is a fungal infection of the feet with itching, scaling and redness. It can be caused by a number of different fungi, including Trichophyton, Epidermophyton and Microsporum." },
    { title: "Ringworm", content: "Ringworm (Tinea Corporis) can appear in the form of a red or silver rash anywhere on the body. It is usually ring-shaped and is most commonly caused by the fungus Trichophyton rubrum." },
    { title: "Onychomycosis", content: "Onychomycosis is a fungal infection of the toenails or fingernails that can involve any component of the nail, including the matrix, bed or plate. It can cause pain, discomfort and disfigurement. Onychomycosis is caused by various fungal organisms, the most common being dermatophyte. Yeast and moulds also cause nail infections." },
    { title: "Tinea Versicolor", content: "Tinea Versicolor or pityriasis versicolor is a common condition that causes small patches of skin to become scaly and discoloured. They can be darker or lighter than the surrounding skin, or even red or pink. The condition is caused by a yeast called Malassezia, which lives on the skin of most people without causing any problems." },
    { title: "Cutaneous Candidiasis", content: "Cutaneous Candidiasis can involve almost any skin area of the body, but mostly occurs in warm, moist, creased areas such as the armpits and groin. Candida is the most common cause of nappy rash in infants. Candida is also common in people who are obese or have diabetes. Antibiotics, steroid therapy and chemotherapy increase the risk of cutaneous Candidiasis." },
  ];

  return (
    <div>
      <DermatologyNav />
        <DermatologyHero />
    
    <section className=" relative  flex   flex-col md:flex-row items-center justify-between px-6 md:px-16 py-12 md:py-24 bg-white">
      {/* Text Content */}
      <motion.div  
        initial={{ opacity: 0, x: -50 }} 
        animate={{ opacity: 1, x: 0 }} 
        transition={{ duration: 0.8 }}
        className="md:w-1/2 text-left"
      >
        <h1 className="text-4xl md:text-6xl font-bold leading-tight mt-2">
        
        Laser Tattoo Removal

        </h1>
        <p className="text-lg text-gray-600 mt-6 ">Lasers work by directing energy toward ink in the skin with highly concentrated colored light beams. These laser beams break up ink particles into tiny fragments, which are later cleared up by the body’s scavenging cells. This process of fragmenting the ink particles requires numerous sessions depending on the depth of the ink level. The procedure is bloodless and no incisions are made. The laser selectively targets the pigment of the tattoo without damaging the surrounding skin. With deeper penetration of the skin and multiple sessions, however, the heat generated by the lasers may cause pain and blister formation. Even though laser technology is refined, the chance of scarring is always present with multiple treatments. This is not only true for laser tattoo removal, but with nearly all tattoo removal methods.</p>
        
        

        <h1 className="text-gray-900 text-3xl mt-8">
        Who is the candidate for laser tattoo removal ?
        </h1>
        <ul  className="pl-5 text-lg mt-4 space-y-2 top-3 gap-11">
                <li className="flex  ">
                  <ChevronRight className="text-red-400 w-11" />
                  Individuals with fair skin and superficially placed tattoos on the arms, chest, buttocks or legs are the best candidates. Tattoos on dark-skinned individuals, or tattoos on the ankles or fingers (areas where there is less body fat), are the most difficult to treat and results are more variable. A thorough discussion with a tattoo removal specialist can better determine the potential success rate of laser tattoo removal for any given tattoo and skin type. Consulting with a professional and reputable tattoo removal specialist who is experienced and understands the procedure is important to ensure proper treatment and candidacy.
                </li>
        </ul>
        <h1 className="text-gray-900 text-3xl mt-8">Can all tattoos be removed ?</h1>
        <ul  className="pl-5 text-lg mt-4 space-y-2 top-3 gap-11">
                <li className="flex ">
                  <ChevronRight className="text-red-400 w-11" />
                  Unfortunately, not all tattoos can be removed completely, but the majority can be. Tattoos are meant to be permanent, and with recent ink technology and professional tattoo artists improving their skills, tattoos imprinted in the last decade are very difficult to remove. Even with the best technique, some residual scarring remains in a few cases.
                </li>
        </ul>
        <h1 className="text-gray-900 text-3xl mt-8">What determines the success of tattoo removal ?</h1>
        <ul  className="pl-5 text-lg space-y-2 top-3 mt-4 gap-11">
                <li className="flex ">
                  <ChevronRight className="text-red-400 w-24" />
                  Complete removal of a tattoo is based on several things. The size, location, application, age of the tattoo (newer tattoos are generally more difficult to remove), and color of the tattoo all factor in, as well as the health of the patient. A patient’s health is a determining factor because it will determine how well the body is able to heal after the procedure.
                </li>
        </ul>
        

        
        
      </motion.div>
      
      {/* Image Section */}
      <motion.div 
        initial={{ opacity: 0, x: 50 }} 
        animate={{ opacity: 1, x: 0 }} 
        transition={{ duration: 0.8, delay: 0.3 }}
        className="md:w-1/2 flex justify-end mt-10 md:mt-0 relative"
      >
        <div className="relative mb-36 w-full max-w-md">
          <img 
            src={hairreductionImg} 
            alt="Beauty Clinic" 
            className=" rounded-lg w-[50vw] h-[50vh] shadow-lg"
          />
          <div className="absolute bottom-0 right-0  bg-amber-100 -z-10"></div>
        </div>

      </motion.div>
    </section>
    <DermatologyFooter />
        
    </div>
  );
};



export default TattoRemovel;
